BaseUrl= "http://bdapp.org/"
LanguageCode= "zh-CN"
Title= "刘仁斐的博客"
paginate = 5
DisqusShortname = "Raphael"
Copyright = "All rights reserved - 2015"
canonifyurls = true
publishdir = "public"
contentdir = "content"
layoutdir = "layouts"
[params]
  description = "冷暖自知，岁月静好"
  cover = "images/cover.jpg"
  author = "raphael-liu"
  authorlocation = "China"
  authorwebsite = "http://cq01-rdqa-dev100.cq01.baidu.com:8888/"
  bio= "my bio"
  logo = ""
  googleAnalyticsUserID = "UA-70952321-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feedly.com/i/subscription/feed/http://cq01-rdqa-dev100.cq01.baidu.com:8888//atom.xml"
  githubName = "raphael-liu"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
